### ISSUE TITLE
bug: Module not found: Can't resolve '@acme/db/client;

### ISSUE THREAD

**Issue by sonipranjal** [t3-oss/create-t3-turbo#1145]
### Provide environment information

System:
    OS: macOS 14.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 679.89 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.15.0 - ~/.nvm/versions/node/v20.15.0/bin/node
    Yarn: 1.22.17 - ~/.yarn/bin/yarn
    npm: 10.7.0 - ~/.nvm/versions/node/v20.15.0/bin/npm
    pnpm: 9.6.0 - ~/.nvm/versions/node/v20.15.0/bin/pnpm
    bun: 1.0.0 - ~/.bun/bin/bun
    Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman

### Describe the bug

I think you might wanna resolve this issue, did nothing, cloned the repo and installed everything using pnpm i and after running the nextjs app, found this out, most probably due to incorrect exports in db package? 

"exports": {
    ".": {
      "types": "./dist/index.d.ts",
      "default": "./dist/index.js"
    },
    "./client": {
      "types": "./dist/client.d.ts",
      "default": "./dist/client.js"
    },
    "./schema": {
      "types": "./dist/schema.d.ts",
      "default": "./dist/schema.js"
    }
  },
  
<img width="826" alt="Screenshot 2024-08-11 at 4 23 08 PM" src="https://github.com/user-attachments/assets/276d852a-5915-40be-a28e-d4d3cb62f8be">

### Link to reproduction

pnpm i && cd apps/nextjs && pnpm run dev

### To reproduce

pnpm i && cd apps/nextjs && pnpm run dev

**Comment by ahkhanjani** [comment]
May I see the files inside your `packages/db/dist`?

**Comment by sonipranjal** [comment]
Yeah i figured it out, i need to build everytime i change my db schema, in the previous version of t3 turbo, i didn't have to do this

**Comment by juliusmarminge** [comment]
`turbo run dev` runs watchers that emits declaration files whenever packages changes

Live types are not very performant as the repo grows which is why we have opted for emitting declaration files instead. If you have a small repo with a small drizzle schema, a small trpc router without a lot of zod schemas, you may get away with live types and rely on typescript inference but ymmv

**Comment by sonipranjal** [comment]
Thanks Julius! Appreciate your efforts.

**Comment by smblee** [comment]
This happens on build time now

**Comment by MJSPollard** [comment]
> `turbo run dev` runs watchers that emits declaration files whenever packages changes
> 
> Live types are not very performant as the repo grows which is why we have opted for emitting declaration files instead. If you have a small repo with a small drizzle schema, a small trpc router without a lot of zod schemas, you may get away with live types and rely on typescript inference but ymmv

Be that as it may, I don't understand the decision to do this. It essentially breaks a lot of the hot reloading to the point where it becomes a massive pain to use. I had to change turbo dev script persistent to true and run tsc --watch on my package dev scripts otherwise I would make changes in the api and nothing would actually happen until i rebuilt which is so annoying to do on every little change especially when debugging. What's the point of transpiling the packages in next.config when they wont update a lot of the time anyway.

**Comment by ahkhanjani** [comment]
> What's the point of transpiling the packages in next.config when they wont update a lot of the time anyway.

If you depend a lot on small packages rather than writing most of your components in the apps themselves, they will update a lot. It depends on your specific project/monorepo structure. If you have a large codebase with lots of shared code (packages) then you will be updating the packages often. If that's not the case then you probably don't need a monorepo in the first place.

I agree that the breaking of tRPC go to definition is really annoying. I've already opened an [issue](https://github.com/trpc/trpc/issues/5933) but I don't expect much. There is probably no fix. And yes you could argue that emitting declaration files as a default maybe too much. The problem is that Zod is just too slow and I'm pretty sure the reason this decision was made was due to some [low performace reports](https://github.com/t3-oss/create-t3-turbo/issues/277).
