### ISSUE TITLE
[Improvement] Any plan to use Solito?

### ISSUE THREAD

**Issue by wezter96** [t3-oss/create-t3-turbo#29]
I just started looking into this project because I wanted to see if I could possibly move my Solito project to this starter but it seems like there's no shared navigation and no sharing of components / screens in this repo unless I'm missing something.

Is Solito something you're planning to add later on?

Saw someone else had something started with Solito but probably won't be as nicely maintained as what you're building and I struggled deploying it.
https://github.com/chamatt/create-kaol-app

**Comment by VidunderGunder** [comment]
You might like this:
https://github.com/VidunderGunder/create-xp-app

**Comment by izakfilmalter** [comment]
Seems like a big miss. I get the desire to be lite weight and the branding issue, rename it to `Tolito` 🥁. Would you be open to a pr that adds solito? 

What I guess I am getting at is the big value prop of TRPC, and by extension T3 is code sharing. Your import your API on the server and the client and use it in a transparent manner. I think you want that same experience if you are gonna put expo into it. At the same time, I wouldn't include Solito in regular T3 since it has no use there.

I just think the value prop of Solito is so good and aligns with T3, promote code sharing between Next and Expo. Here is a good example of the amount of code sharing you can have between Next and Expo: https://github.com/tamagui/tamagui/tree/master/starters/next-expo-solito

**Comment by juliusmarminge** [comment]
> Seems like a big miss. I get the desire to be light weight and the branding issue, rename it to `Tolito` 🥁. Would you be open to a pr that adds solito? 
> 
> 
> 
> What I guess I am getting at is the big value prop of TRPC, and by extension T3 is code sharing. Your import your API on the server and the client and use it in a transparent manner. I think you want that same experience if you are gonna put expo into it. At the same time, I wouldn't include Solito in regular T3 since it has no use there.
> 
> 
> 
> I just think the value prop of Solito is so good and aligns with T3, promote code sharing between Next and Expo. Here is a good example of the amount of code sharing you can have between Next and Expo: https://github.com/tamagui/tamagui/tree/master/starters/next-expo-solito

There are so many templates out there that uses Solito (even official ones from the creator himself) so if anyone wants to add it it's really not that hard.

**Comment by redbar0n** [comment]
maybe a solito branch would be a compromise
