### ISSUE TITLE
bug: No compile-time errors in dev, consecutive errors in build

### ISSUE THREAD

**Issue by Tobjoern** [t3-oss/create-t3-turbo#322]
### Provide environment information

System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 AMD Ryzen 7 2700 Eight-Core Processor
    Memory: 14.65 GB / 31.95 GB
  Binaries:
    Node: 16.19.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD

### Describe the bug

I have added two very obvious, compile-time errors to index.tsx and _app.tsx, namely:
`const x: string = 4` and `const a: string = 4`.

### Issue 1:
When running the dev script, I would expect the code not to compile, but to tell me about this issue,
so I could fix it, but the dev script runs successfully and I can use the app.

### Issue 2:
When running the build script, the error in '_app.tsx' is actually shown, but not the one in 'index.tsx'.
The error in 'index.tsx' is only shown, once I fix the errors in '_app.tsx' -> Meaning the compiler stops after the first error.
This leads to extremely cumbersome and annoying issues, when moving a component library from one file to the other and having to deal with all the errors consecutively.

### Link to reproduction

https://github.com/Tobjoern/ts-turbo-demo

### To reproduce

Download the repo,
'pnpm install',
'pnpm run dev',
'pnpm run build'.

**Comment by juliusmarminge** [comment]
I don't see how this has to do with t3-turbo. This is how it works in any Next.js app.

- a typeerror in dev shouldn't kill your server - that would be quite bad DX.
- build is cancelled after first error cause what if you'd have 10 more errors following just cause you had that 1st error? should your entire terminal be literred or just show the root cause?

here's a sandbox with a minimal next.js app: https://stackblitz.com/edit/nextjs-ce2hjm?file=pages/index.tsx

And here's a small demo, as you can see build stops at the first error it sees:
https://cln.sh/fLz4BZ4b

**Comment by Tobjoern** [comment]
I see how this error has nothing to do with t3-turbo,
but I disagree with your assessment that this would be quite bad DX.
Let's say I move my 'FormGroup' component from 'shared' to 'inputs' and this very component is used in 100 other components.
With the current setup, I would have to run 'npm run build' 100 times, and jump to each component separately, to get it to work again.

I find the way nuxt.js handles this to be a lot better.

**Comment by juliusmarminge** [comment]
I suggestiv you open an issue in Next.js then
