### ISSUE TITLE
How to sync API and mobile app versions

### ISSUE THREAD

**Issue by nikita-rudenko** [t3-oss/create-t3-turbo#407]
I expect to release a mobile app to Google Play and Apple Store. And I know that on mobile platforms updates are going slow. Many users can still use older versions of the app that might call API that changed in the newest version. How can I make sure that even on older versions of the app, API requests won't break?

Thanks for your work, Julius 🙏

**Comment by juliusmarminge** [comment]
You can use Expo OTA Updates without going through the review process for a lot of changes that don't touch the native layers.

Otherwise you're gonna have to be careful when removing fields, changing inputs and make sure to keep backwards compatibility until you know that noone's using an old field etc
