### ISSUE TITLE
Question: Why drizzle instead of prisma?

### ISSUE THREAD

**Issue by raiomarco** [t3-oss/create-t3-turbo#533]
Excuse-me for asking about it, but i couldn't find anywhere why this was changed...

> And why this is relevant?

I never heard of drizzle, but, ok, new tech, cool... So i tried it

After some experiments, i decided that i just.. like prisma a lot more, and then i was asking myself "why they changed the prisma? there's should be a reason for it right?", and here i am, asking it :)

**Comment by juliusmarminge** [comment]
Performance and edge runtime compatibility

**Comment by raiomarco** [comment]
Oh thanks, do you think that maybe if i documenting how to revert to prisma, it would be usefull here?

**Comment by juliusmarminge** [comment]
Technically it could just be include är in the warning message at the top of the readme that says that we moved on to appdir, listing a link diffing the commits necessary?

If you wanna go the extra mile include a `details>` block with specific things?

**Comment by anisimovv** [comment]
@juliusmarminge maybe not related, but I think it can be useful note in future. If you try to use drizzle with postgres adapter, app will crash. And the reason is that trpc endpoint configured to run on the edge, meanwhile postgres not support running on edge. 

I mean maybe it is good thing to mention in readme if adapter is not supports edge runtime - you should use node runtime.

**Comment by juliusmarminge** [comment]
PRs accepted for documentation improvements if you're willing to make them!

**Comment by ludalex** [comment]
Sorry to bring this up but since Edge Runtime compatibility, at least for Vercel deployments, seems like it's no longer an issue as they shifted to have everything Node.js based, wouldn't it make sense to have bring back Prisma as a choice when creating a new project?

The only big difference, aside from making a separate, optional config to use Prisma as the chosen ORM, is the Auth.js config, which for it to work with the Next.js middleware which still uses the Edge Runtime should be modified to have a [separate config](https://authjs.dev/guides/edge-compatibility#split-config) from the actual instantiated Auth.js which would export the edge-incompatible `PrismaAdapter`.
