### ISSUE TITLE
bug: 'Cannot find package 'mysql2' imported from '/root/create-t3-turbo/node_modules/drizzle-orm/mysql2/index.mjs'

### ISSUE THREAD

**Issue by jamesjohnoliver** [t3-oss/create-t3-turbo#658]
### Provide environment information

  System:
    OS: Linux 5.10 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1260P
    Memory: 7.12 GB / 7.62 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.17.1 - /usr/bin/node
    Yarn: 1.22.19 - /mnt/c/Users/james/AppData/Roaming/npm/yarn
    npm: 9.6.7 - /usr/bin/npm

### Describe the bug

Can't get the template running. 

### Link to reproduction

https://github.com/t3-oss/create-t3-turbo/commit/10ffa526904c93612c219677717ee3848205065a

### To reproduce

Cloned from [10ffa52](https://github.com/t3-oss/create-t3-turbo/commit/10ffa526904c93612c219677717ee3848205065a), followed readme instructions up to `pnpm dev`, ran into this error.

**Comment by juliusmarminge** [comment]
Ah - drizzle-kit currently requires the mysql (or pg for Postgres) driver to run studio. They will fix this in the next update but for now just install mysql2 as a dev dependency to get studio working. (it won't be used to actually query your db from your app since that's done by the planet scale http adapter)

**Comment by jamesjohnoliver** [comment]
Thanks Julius!

**Comment by jamesjohnoliver** [comment]
I'm just going to filter out drizzle-kit when I run 'dev' for now.
