### ISSUE TITLE
feat: Docker for development with hot reload

### ISSUE THREAD

**Issue by digoburigo** [t3-oss/create-t3-turbo#769]
### Describe the feature you'd like to request

I want to know how to make a Docker for development. Where it hot reload even if some `package` change. Thats possible?

### Describe the solution you'd like to see

Some Docker example or some guidance on how to make this work

**Comment by noxify** [comment]
Hi,

since I have to think about using ODBC/JDBC in one of my node apps, I want to keep my local system as clean as possible (not interested to install Java locally 🙈).

The solution is docker with HMR.

I found this article which could be the solution.

https://medium.com/@elifront/best-next-js-docker-compose-hot-reload-production-ready-docker-setup-28a9125ba1dc

While reading the article, I remembered that there was a request (this issue) with a similar requirement.

Haven't had the time to test it in detail but I think it could be enough to change the `yarn` commands with `pnpm`.

Does this help?
