### ISSUE TITLE
feat: Set cookies via Api

### ISSUE THREAD

**Issue by hasanaktas** [t3-oss/create-t3-turbo#797]
### Describe the feature you'd like to request

I use my own authentication structure instead of next-auth. I can read the cookie via the API now, but I couldn't figure out how to set it. I think I need to change some things on the createContext side. I can send tokens as response from the API and set cookies with server action, but I want to set the cookies directly from the TRPC API.

### Describe the solution you'd like to see

I have no idea

**Comment by juliusmarminge** [comment]
You cannot set headers/cookies after the initial response has been sent (streaming), if you need that you'll need to set cookies in middleware

**Comment by juliusmarminge** [comment]
Alternatively replace the streaming link with a normal batchLink here: https://github.com/t3-oss/create-t3-turbo/blob/d01bb420feef1fbdc89eb3583316e7b57990c784/apps/nextjs/src/trpc/react.tsx#L28

Note that streaming queries wont work then, since all requests in the batch must succeed before any response is sent
